# © 2026 erik · https://erik.xyz · erik@erik.xyz​‍‍​​‍​‍​‍‍‍​​‍​​‍‍​‍​​‍​‍‍​‍​‍‍​​‍​‍‍‍​​‍‍‍‍​​​​‍‍‍‍​​‍​‍‍‍‍​‍​
[package]
name = "xd-carving"
version.workspace = true
edition.workspace = true

[dependencies]
xd-device = { path = "../xd-device" }

[dev-dependencies]
xd-fixtures = { path = "../xd-fixtures" }
xd-fs-exfat = { path = "../xd-fs-exfat" }
xd-fs-fat = { path = "../xd-fs-fat" }
tempfile = { workspace = true }
