# © 2026 erik · https://erik.xyz · erik@erik.xyz​‍‍​​‍​‍​‍‍‍​​‍​​‍‍​‍​​‍​‍‍​‍​‍‍​​‍​‍‍‍​​‍‍‍‍​​​​‍‍‍‍​​‍​‍‍‍‍​‍​
[package]
name = "xd-core"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
xd-device = { path = "../xd-device" }
xd-carving = { path = "../xd-carving" }
xd-fs-exfat = { path = "../xd-fs-exfat" }
xd-fs-fat = { path = "../xd-fs-fat" }
base64 = { workspace = true }
rustix = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
xd-fixtures = { path = "../xd-fixtures" }
