# © 2026 erik · https://erik.xyz · erik@erik.xyz​‍‍​​‍​‍​‍‍‍​​‍​​‍‍​‍​​‍​‍‍​‍​‍‍​​‍​‍‍‍​​‍‍‍‍​​​​‍‍‍‍​​‍​‍‍‍‍​‍​
[package]
name = "xd-fs-fat"
version.workspace = true
edition.workspace = true

[dependencies]
xd-device = { path = "../xd-device" }

[dev-dependencies]
xd-fixtures = { path = "../xd-fixtures" }
tempfile = { workspace = true }
