# © 2026 erik · https://erik.xyz · erik@erik.xyz​‍‍​​‍​‍​‍‍‍​​‍​​‍‍​‍​​‍​‍‍​‍​‍‍​​‍​‍‍‍​​‍‍‍‍​​​​‍‍‍‍​​‍​‍‍‍‍​‍​
[package]
name = "xd-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
xd-core = { path = "../xd-core" }
xd-device = { path = "../xd-device" }

[dev-dependencies]
tempfile = { workspace = true }
xd-fixtures = { path = "../xd-fixtures" }
